# **Competencia 1 - CC6205 Natural Language Processing 📚**

**Integrantes:**

- Sebastián Flores

- Felipe Ortuzar

- Romina Pérez

**Usuario del equipo en CodaLab:**

**Fecha límite de entrega 📆:** Jueves 29 de Abril.

**Tiempo estimado de dedicación:**

## **Objetivo**

En esta tarea grupal participarán de una competencia estilo [Kaggle](https://www.kaggle.com/) pero utilizando la página [CodaLab](https://codalab.org/). El objetivo es trabajar en la clasificación de tweets  según su intensidad de emoción, esto corresponde a la task de clasificación de texto. 

Tendrán a su disposición 4 datasets de tweets con distintas emociones: `anger`, `fear`, `sadness` y `joy`. Deberán crear un clasificador para cada uno de estos datasets que indique la intensidad de dicha emoción en sus tweets (`low`, `medium`, `high`). 

## **Instrucciones**



- La competencia consiste en resolver 4 problemas de clasificación **distintos**, cada uno con tres clases posibles. Por cada problema deberán crear un clasificador distinto. La evaluación de la competencia se realiza en base a 3 métricas: `AUC`, `Kappa` y `Accuracy`. Los mejores puntajes en cada una de estas métricas serán quienes ganen la competencia.

- Para comenzar se les entregará en este notebook la estructura del informe a entregar y el código de un baseline con el cuál pueden comparar los resultados de sus experimentos. Este baseline consiste en la creación de features y una clasificación simple siguiendo el paradigma de Machine Learning empírico. Los puntajes obtenidos por el baseline los pueden visualizar en el link de CodaLab buscando al usuario **cc6205**. Esperamos que los superen fácilmente 😉

- Para participar, deben registrarse en CodaLab y luego ingresar a la competencia usando el siguiente [link](https://competitions.codalab.org/competitions/30330?secret_key=b2ed0be7-bf23-42a1-9400-f85fa1b7bae7). 

- Está permitido hacer grupos de máximo 3 alumnos. Cada grupo debe tener un nombre de equipo, para ello en CodaLab pueden dirigirse a settings y luego cambiar el Team Name. Sólo una persona debe administrar la cuenta del grupo y se verificará que no se hayan creado múltiples cuentas por grupo.

- En total pueden hacer un **máximo de 4 submissions**, hagan muchos experimentos probando en el conjunto de test antes de realizar el envío.

- Es importante que hagan varios experimentos incorporando técnicas como [cross-validation](https://es.wikipedia.org/wiki/Validaci%C3%B3n_cruzada#:~:text=La%20validaci%C3%B3n%20cruzada%20o%20cross,datos%20de%20entrenamiento%20y%20prueba.) o [random sampling](https://towardsdatascience.com/the-5-sampling-algorithms-every-data-scientist-need-to-know-43c7bc11d17c) antes de enviar sus predicciones a CodaLab, ya que les puede dar un mejor indicio del nivel de generalización de sus modelos. 

- Asegúrense que la distribución de las clases sea balanceada en las particiones de training y testing debido a que existe un desbalanceo. 

- Verificar que el formato de la submission coincida con el de la competencia. De lo contrario, se les será evaluado incorrectamente ya que el Script de evaluación espera como input dicho formato. En el código de las métricas pueden verificar cómo son los inputs.

- No se limiten a los contenidos vistos ni a scikit ni a este baseline. No tienen restricciones entre utilizar Deep Learning o Machine Learning empírico. Si reutilizan gran cantidad de código de alguna página por favor mostrar la referencia en su código. ¡Usen todo su conocimiento e ingenio en mejorar sus sistemas para poder ganar la competencia! 

- **Es requisito entregar el reporte con el código y haber participado en la competencia para ser evaluado. Un código sin reporte o un reporte sin código serán evaluados con la nota mínima.**

- Todas las dudas escríbanlas en el canal de Discord de competencias. Los emails que lleguen al equipo docente serán remitidos a ese medio.

**Importante**: Recuerden poner su nombre y el de su usuario o de equipo (en caso de que aplique) en el reporte. NO serán evaluados Notebooks sin nombre.

----------------------------------------

## **Reporte a entregar**

Uno de los puntos claves en la evaluación de esta competencia es elaborar un informe claro y preciso, argumentando las decisiones tomadas al momento de crear sus modelos para que el cuerpo docente pueda entenderlos. La estructura que debe contener es la siguiente:

1.	**Introducción**: Presentar brevemente el problema a resolver, incluyendo la formalización de la task (cómo son los inputs y outputs del problema) y los desafíos que ven al analizar el corpus entregado. (**0.5 puntos**)
2.	**Representaciones**: Describir los atributos y representaciones usadas como entrada de los clasificadores, **recordar** que para entrenar modelos el input debe tener su representación numérica. Si bien, con Bag of Words (**baseline**) ya se comienzan a percibir buenos resultados, pueden mejorar su evaluación agregando más atributos y representaciones diseñadas a mano, sean lo más creativos posible. Más abajo encontrarán una lista de estos posibles atributos que les podrá ser de utilidad. (**1 punto**)
3.	**Algoritmos**: Describir **brevemente** los algoritmos de clasificación usados, tanto si fueron algoritmos ya vistos en clases o bien arquitecturas de Deep Learning. (**0.5 puntos**)
4.	**Métricas de evaluación**: Describir brevemente las métricas utilizadas en la evaluación, indicando qué miden y su interpretación. (**0.5 puntos**)

5.  **Diseño experimental**: Esta es una de las secciones más importantes del reporte. Deben describir minuciosamente los experimentos que realizarán en la siguiente sección. Describir las variables de control que manejarán, algunos ejemplos pueden ser: Los parámetros de los clasificadores, parámetros en las funciones con que procesan los textos y los transforman, parámetros para el cross-validation, particiones de datos utilizadas, etc. En caso que utilicen redes neuronales, ser claros con el conjunto de hiperparámetros que probarán, la decisión en las funciones de optimización, función de pérdida,  regulación, etc. Básicamente explicar qué es lo que veremos en la siguiente sección.
(**1 punto**)

6.	**Experimentos**: Incluyan todo el código de sus experimentos aquí. ¡Es vital haber realizado varios experimentos para sacar una buena nota! (**1.5 puntos**)

7. **Resultados**: Comparar los resultados obtenidos utilizando diferentes algoritmos y representaciones.  Pueden mostrar los resultados sobre la partición de validación en caso que la generen o sobre los resultados del conjunto de testing. Mostrar los resultados en alguna tabla, pueden poner aquí también los resultados obtenidos al realizar la submission. (**0.5 puntos**)

8. **Conclusiones**:  Discutir resultados, proponer trabajo futuro. (**0.5 puntos**)

## **Descripción Baseline**

` `
El baseline de la sección **Experimentos** contiene un código básico que resuelve la task y es el modelo subido por **cc6205-baseline** a la competencia. Pueden modificar el código como quieran siempre y cuando no cambien las funciones de las métricas y el formato en que se suben los archivos a la competencia, ya que ese es el formato en que realizamos la evaluación. En concretro, el baseline hace lo siguiente:
` `

- Obtiene los datasets desde el repositorio del curso.
- Divide los datasets en train (datos que están etiquetados) y target set (datos no etiquetados para la competencia). Además, por cada dataset en train, se divide en un conjunto de entrenamiento y uno de prueba. Aquí la mejor práctica sería cambiar el código para obtener un conjunto de entrenamiento, validación y prueba.

- Crea un Pipeline que: 
    - Crea features personalizados para la representación numérica.
    - Transforma los dataset a bag of words (BoW).  
    - Entrena un clasificador usando cada train set.
- Clasifica y evalua el sistema creado usando el test set.
- Clasifica el target set.
- Genera una submission con el target en formato zip en el directorio en donde se está ejecutando el notebook. 

` `

Algunas pistas sobre como mejorar el rendimiento de los sistemas que creen. (Esto tendrá mas sentido cuando vean el código)

- **Vectorizador**: Investigar los modulos de `nltk`, en particular, `TweetTokenizer`, `mark_negation` para reemplazar los tokenizadores. También, el parámetro `ngram_range` (Ojo que el clf naive bayes no debería usarse con n-gramas, ya que rompe el supuesto de independencia). Además, implementar los atributos que crean útiles desde el listado del enunciado. Investigar también el vectorizador tf-idf.

- **Clasificador**: Investigar otros clasificadores más efectivos que naive bayes. Estos deben poder retornar la probabilidad de pertenecia de las clases (ie: implementar la función `predict_proba`).

- **Features**: Recuerden que pueden implementar todas las features que se les ocurra! Aquí les adjuntamos algunos ejemplos:
    -	Word n-grams.
    -	Character n-grams. 
    -	Part-of-speech tags.
    -	Sentiment Lexicons (Lexicon = A set of words with a label or associated value.).
        - Count the number of positive and negative words within a sentence.
        - If the lexicon has associated intensity of feeling (for example in a decimal), then take the average of the intensity of the sentence according to the feeling, the sum, etc.
        -	A good lexicon of sentiment: [Bing Liu](http://www.cs.uic.edu/~liub/FBS/opinion-lexicon-English.rar) 
        - A reference with a lot of [sentiment lexicons](https://medium.com/@datamonsters/sentiment-analysis-tools-overview-part-1-positive-and-negative-words-databases-ae35431a470c). 
    -	The number of elongated words (words with one character repeated more than two times).
    -	The number of words with all characters in uppercase.
    -	The presence and the number of positive or negative emoticons.
    -	The number of individual negations.
    -	The number of contiguous sequences of dots, question marks and exclamation marks.
    -	Word Embeddings: Here are some good ideas on how to use them.
    https://stats.stackexchange.com/questions/221715/apply-word-embeddings-to-entire-document-to-get-a-feature-vector

- **Reducción de dimensionalidad**: También puede serles de ayuda. Referencias [aquí](https://scikit-learn.org/stable/modules/unsupervised_reduction.html).

- Por último, pueden encontrar mas referencias de cómo mejorar sus features, el vectorizador y el clasificador [aquí](https://affectivetweets.cms.waikato.ac.nz/benchmark/).

# **Entregable.**

## **1. Introducción**

    Escriba su introducción aquí

## **2. Representaciones**

    Escriba sus decisiones para la representación

## **3. Algoritmos**

    Explique los algoritmos utilizados

## **4. Métricas de Evaluación**

- AUC: ...
- Kappa: ...
- Accuracy: ...


## **5. Diseño experimental**

    Descripción de la metodología 

## **6. Experimentos**

### Importar librerías

In [75]:
import pandas as pd
import os
import numpy as np
import shutil
import string
import re

from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.metrics import confusion_matrix, cohen_kappa_score, classification_report, accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator, TransformerMixin

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.tokenize import word_tokenize, TweetTokenizer
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.stem import SnowballStemmer

pd.set_option('display.max_colwidth', None)
import nltk
nltk.download('punkt')
nltk.download('stopwords')

punct = list(string.punctuation)
stop_words = list(stopwords.words('english'))
stemmer = SnowballStemmer('english')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


### Definir métodos de evaluación (**NO tocar este código**)

Estas funciones están a cargo de evaluar los resultados de la tarea. No deberían cambiarlas.


In [3]:
def auc_score(test_set, predicted_set):
    high_predicted = np.array([prediction[2] for prediction in predicted_set])
    medium_predicted = np.array(
        [prediction[1] for prediction in predicted_set])
    low_predicted = np.array([prediction[0] for prediction in predicted_set])
    high_test = np.where(test_set == 'high', 1.0, 0.0)
    medium_test = np.where(test_set == 'medium', 1.0, 0.0)
    low_test = np.where(test_set == 'low', 1.0, 0.0)
    auc_high = roc_auc_score(high_test, high_predicted)
    auc_med = roc_auc_score(medium_test, medium_predicted)
    auc_low = roc_auc_score(low_test, low_predicted)
    auc_w = (low_test.sum() * auc_low + medium_test.sum() * auc_med +
             high_test.sum() * auc_high) / (
                 low_test.sum() + medium_test.sum() + high_test.sum())
    return auc_w


def evaluate(predicted_probabilities, y_test, labels, dataset_name):
    # Importante: al transformar los arreglos de probabilidad a clases,
    # entregar el arreglo de clases aprendido por el clasificador.
    # (que comunmente, es distinto a ['low', 'medium', 'high'])
    predicted_labels = [
        labels[np.argmax(item)] for item in predicted_probabilities
    ]

    print('Confusion Matrix for {}:\n'.format(dataset_name))
    print(
        confusion_matrix(y_test,
                         predicted_labels,
                         labels=['low', 'medium', 'high']))

    print('\nClassification Report:\n')
    print(
        classification_report(y_test,
                              predicted_labels,
                              labels=['low', 'medium', 'high']))
    # Reorder predicted probabilities array.
    labels = labels.tolist()
    
    predicted_probabilities = predicted_probabilities[:, [
        labels.index('low'),
        labels.index('medium'),
        labels.index('high')
    ]]
    
    
    auc = round(auc_score(y_test, predicted_probabilities), 3)
    print("Scores:\n\nAUC: ", auc, end='\t')
    kappa = round(cohen_kappa_score(y_test, predicted_labels), 3)
    print("Kappa:", kappa, end='\t')
    accuracy = round(accuracy_score(y_test, predicted_labels), 3)
    print("Accuracy:", accuracy)
    print('------------------------------------------------------\n')
    return np.array([auc, kappa, accuracy])

### Datos



In [4]:
# Datasets de entrenamiento.
train = {
    'anger': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/train/anger-train.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity']),
    'fear': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/train/fear-train.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity']),
    'joy': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/train/joy-train.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity']),
    'sadness': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/train/sadness-train.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'])
}
# Datasets que deberán predecir para la competencia.
target = {
    'anger': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/target/anger-target.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'], na_values=['NONE']),
    'fear': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/target/fear-target.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'], na_values=['NONE']),
    'joy': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/target/joy-target.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'], na_values=['NONE']),
    'sadness': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/target/sadness-target.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'], na_values=['NONE'])
}

In [5]:
# Ejemplo de algunas filas aleatorias del dataset etiquetado:
train['anger'].sample(5)

id  \
676  10676   
137  10137   
478  10478   
924  10924   
425  10425   

                                                                                                                                           tweet  \
676  Nurse practitioner: 'you look pretty bad. No offense of course.'  \n\nThank you, that really added that spark of positivity I needed today.   
137     To'Why can't we brothers protect one another? No one's serious, and it makes me furious. Don't be misled, just think of Fred.' #mayfield   
478          Now that @Jasmine_Wrn has snapchat back it's a constant battle to see who can get the ugliest snap of one another 😂🙃 #snap survival   
924                                                                       Anger, resentment, and hatred are the destroyer of your fortune today.   
425                                                  I just love it when people make plans for me without actually including me in this process    

     class sentiment_intensity  
676  anger              medium  
137  anger              medium  
478  anger              medium  
924  anger              medium  
425  anger              medium

In [6]:
# Ejemplo de algunas filas aleatorias del dataset no etiquetado
target['anger'].sample(5)

id  \
330  11271   
52   10993   
314  11255   
287  11228   
99   11040   

                                                                                                         tweet  \
330                                                   @Dominos_UK worst thing is i have confimation from them    
52                                                               The war is right outside your door  #USAToday   
314                                                               @takumasgirl I fell and heard a snap hffffhj   
287                                                 @alexis_maxwell #bitter hahaha just kidding. its crazy tho   
99   Using multiple combs simultaneously is what I like to call impressive work!!    ;-O #snap #ohsnap #daaamn   

     class  sentiment_intensity  
330  anger                  NaN  
52   anger                  NaN  
314  anger                  NaN  
287  anger                  NaN  
99   anger                  NaN

### Analizar los datos 

En esta sección analizaremos el balance de los datos. Para ello se imprime la cantidad de tweets de cada dataset agrupados por la intensidad de sentimiento.

In [7]:
for dataset_name in train:
    print(f'Dataset: {dataset_name} \n', train[dataset_name].groupby(['sentiment_intensity']).size())
    print('----------------------------------------------------------\n')

Dataset: anger 
 sentiment_intensity
high      163
low       161
medium    617
dtype: int64
----------------------------------------------------------

Dataset: fear 
 sentiment_intensity
high      270
low       288
medium    699
dtype: int64
----------------------------------------------------------

Dataset: joy 
 sentiment_intensity
high      195
low       219
medium    488
dtype: int64
----------------------------------------------------------

Dataset: sadness 
 sentiment_intensity
high      197
low       210
medium    453
dtype: int64
----------------------------------------------------------



In [8]:
full_train = pd.concat(train)
full_train.reset_index(drop=True, inplace=True)

full_target = pd.concat(target)
full_target.reset_index(drop=True, inplace=True)

full = pd.concat([full_train, full_target])
full.reset_index(drop=True, inplace=True)

In [10]:
# NO HAY LINKS EN LOS TWEETS
print('Cantidad de links en los tweets:')
print(full.tweet.str.contains(r"(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))").sum())
print(full.tweet.str.contains(r"(?i)\b((?:http?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))").sum(), '\n\n')

# NO HAY INDICADORES DE RETWEET
print('Hay algún indicador de retweet?')
print(full.tweet.str.contains('RT @').sum())
print(full.tweet.str.contains('Rt @').sum())
print(full.tweet.str.contains('rt @').sum())
print(full.tweet.str.contains('rT @').sum())
# no corresponde a retweet
print(full.tweet[full.tweet.str.contains('RT @')], '\n\n')

# HAY MAILS DENTRO DE LOS TWEETS
print('Hay algun mail?')
print(full.tweet.str.contains(r'\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?').sum())
# full[full.tweet.str.contains(r'\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?')]

# HAY USUARIOS CON PARENTESIS
print('Hay usuarios con paréntesis')
# full[full.tweet.str.contains(r'([(@]+[A-Za-z0-9 ñáéíóú]+[)]+)')]

Cantidad de links en los tweets:
0
0 


Hay algún indicador de retweet?
1
1
3
0
464    @DRUDGE_REPORT @FoxNews good thing the FBI didn't offend them!
Name: tweet, dtype: object 


Hay algun mail?
5
Hay usuarios con paréntesis
/shared-libs/python3.7/py/lib/python3.7/site-packages/pandas/core/strings/accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)


In [18]:
# full[full.tweet.str.contains(r'\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?')]
# full[full.tweet.str.contains(r'([(@]+[A-Za-z0-9 ñáéíóú]+[)]+)')]

In [ ]:
# TweetTokenizer().tokenize("Profit are from 5-20% per day to 100-300% per month.Don't hesitate to contact us for the more results! info@fxventury.com")
# TweetTokenizer().tokenize("Lost Frequencies/Janieck Devy - Reality (Gestort Aber Geil Remix)' is raging at ShoutDRIVE!")
# TweetTokenizer().tokenize("What's a Kali's kitten? [She asked, a frown curling on her fair skinned forehead as he showed her the scar] A cat did - (@ScarredTiger)")

### Custom Features 

Para crear features personalizadas implementaremos nuestros propios Transformers (estandar de scikit para crear nuevas features entre otras cosas). Para esto:

1. Creamos nuestra clase Transformer extendiendo BaseEstimator y TransformerMixin. En este ejemplo, definiremos `CharsCountTransformer` que cuenta caracteres relevantes ('!', '?', '#', '@') en los tweets.
2. Definimos una función cómo `get_relevant_chars` que opera por cada tweet y retorna un arreglo.
3. Hacemos un override de la función `transform` en donde iteramos por cada tweet, llamamos a la función que hicimos antes y agregamos sus resultados a un arreglo. Finalmente lo retornamos.

Esto nos facilitará el trabajo mas adelante. Una Guia completa de las transformaciones predefinidas en scikit pueden encontrarla [aquí](https://scikit-learn.org/stable/data_transforms.html).



In [19]:
class CharsCountTransformer(BaseEstimator, TransformerMixin):
    def get_relevant_chars(self, tweet):
        num_hashtags = tweet.count('#')
        num_exclamations = tweet.count('!')
        num_interrogations = tweet.count('?')
        num_at = tweet.count('@')
         
        return [num_hashtags, num_exclamations, num_interrogations, num_at]

    def transform(self, X, y=None):
        chars = []
        for tweet in X:
            chars.append(self.get_relevant_chars(tweet))
        return np.array(chars)

    def fit(self, X, y=None):
        return self

In [20]:
# Veamos que sucede si ejecutamos el transformer
sample = train['anger'].sample(5, random_state=1).tweet
# train['anger'][train['anger'].tweet.str.contains("http:")]
sample_features = CharsCountTransformer().transform(sample)
print(sample)
print(sample_features)
print(sample_features.ndim)
print(sample_features.shape)

604                                                     @everycolorbot more like every color looks the same #triggered #colorblind 
527    @thomeagle Just to help maintain and boost our status as a world class centre for education, culture and tolerance. #outrage
894                                      i live and die for mchanzo honeymoon crashing and burning the second they move in together
195          @RealBD_ @ReyesAverie 47 unarmed blacks killed by white cops in 2015. That many die every month in Chicago wheres the 
422                                                                                    Drop Snapchat names #bored #snap #swap #pics
Name: tweet, dtype: object
[[2 0 0 1]
 [1 0 0 1]
 [0 0 0 0]
 [0 0 0 2]
 [4 0 0 0]]
2
(5, 4)


In [51]:
a = np.array([['este es un ejemplo de un tweet'],
              ['este es el segundo ejemplo'],
              ['tercer tweet']])
a
b = pd.DataFrame(a, columns=['tweet'])
b
# c = b.to_numpy()
c=np.array(b)
# c = b.to_numpy(dtype=list)
c

array([['este es un ejemplo de un tweet'],
       ['este es el segundo ejemplo'],
       ['tercer tweet']], dtype=object)

In [16]:
re.sub(r"(?<=^|(?<=[^a-zA-Z0-9-_\.]))@([A-Za-z0-9_]+)", "", "What's a Kali's kitten? [She asked, a frown curling on her fair skinned forehead as he showed her the scar] A cat did - (@ScarredTiger)")

"What's a Kali's kitten? [She asked, a frown curling on her fair skinned forehead as he showed her the scar] A cat did - ()"

In [69]:
class Preprocessing(BaseEstimator, TransformerMixin):
    # def __init__(BaseEstimator, TransformerMixin):
        # self. = 
    def tokenize(self, tweet):
        # Elimina los nombres de usuario
        tweet = re.sub(r"(?<=^|(?<=[^a-zA-Z0-9-_\.]))@([A-Za-z0-9_]+)", "", tweet)
        
        # Elimina Emails
        tweet = re.sub(r'\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?', "", tweet)

        # tokeniza para aplicar stemming y eliminar stopwords
        tweet = TweetTokenizer().tokenize(tweet)
        punct2 = punct.copy()
        punct2.remove('!')
        punct2.remove('?')
        tweet = [stemmer.stem(i) for i in tweet if i not in stop_words and i not in punct2]

        return ' '.join(tweet)

    def transform(self, X, y=None):
        chars = []
        for tweet in X:
            chars.append(self.tokenize(tweet))
        # return pd.DataFrame(np.array(chars), columns=['tweet'])
        return np.array(chars)

    def fit(self, X, y=None):
        return self

In [92]:
tweet = TweetTokenizer().tokenize('hola @ke # paza #estoy enojado! ? noc¿')
# punct2.remove('!')
# punct2.remove('?')

[stemmer.stem(i) for i in tweet if i not in stop_words and i not in punct2]

['hola', '@ke', 'paza', '#estoy', 'enojado', '!', '?', 'noc', '¿']

In [205]:
tweet = TweetTokenizer().tokenize('holaaa @ke # paza estoy enojado#! ? noc¿')
print(tweet)
print([1 if re.match("^(a)+.", t) else 0 for t in tweet])
print([1 if re.match('(?:a{2,})*', t) else 0 for t in tweet])
print([re.sub('(?:a{2,})*', '', t) for t in tweet])

['holaaa', '@ke', '#', 'paza', 'estoy', 'enojado', '#', '!', '?', 'noc', '¿']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
['hol', '@ke', '#', 'paza', 'estoy', 'enojado', '#', '!', '?', 'noc', '¿']


In [114]:
for t in tweet:
    for tres in listatres:# ['aaa']
        if re.match(tres, t):
            tres += 1

SyntaxError: invalid syntax (<ipython-input-114-528f18a53572>, line 5)

In [106]:
train['anger']

id  \
0    10000   
1    10001   
2    10002   
3    10003   
4    10004   
..     ...   
936  10936   
937  10937   
938  10938   
939  10939   
940  10940   

                                                                                                                                      tweet  \
0                                          How the fu*k! Who the heck! moved my fridge!... should I knock the landlord door. #angry #mad ##   
1                  So my Indian Uber driver just called someone the N word. If I wasn't in a moving vehicle I'd have jumped out #disgusted    
2                              @DPD_UK I asked for my parcel to be delivered to a pick up store not my address #fuming #poorcustomerservice   
3    so ef whichever butt wipe pulled the fire alarm in davis bc I was sound asleep #pissed #angry #upset #tired #sad #tired #hangry ######   
4             Don't join @BTCare they put the phone down on you, talk over you and are rude. Taking money out of my acc willynilly! #fuming   
..                                                                                                                                      ...   
936   @Jen_ny69 People will always get offended everyone's situation is different! Just because we have kids doesn't mean we have to settle   
937     @gayla_weeks1 I try not to let my anger seep into reviews, but I resent having my time wasted on books like that. Time is precious.   
938                                                                                                    I hope my hustle don't offend nobody   
939                                                     Just watched Django Unchained, Other people may frown, but I titter in delight! 2/5   
940                                                                                          Lol little things like that make me so angry x   

     class sentiment_intensity  
0    anger                high  
1    anger                high  
2    anger                high  
3    anger                high  
4    anger                high  
..     ...                 ...  
936  anger              medium  
937  anger              medium  
938  anger                 low  
939  anger                 low  
940  anger              medium  

[941 rows x 4 columns]

In [101]:
class CrearVariables(BaseEstimator, TransformerMixin):

    def mayus(self, tweet):
        tweet = TweetTokenizer().tokenize(tweet)
        tweet = [1 for t in tweet if t.upper() == t]
        tot = sum(count)
        return tot

    def exclamaciones(self, tweet):
        tweet = TweetTokenizer().tokenize(tweet)
        tweet = [1 for t in tweet if t == '!' or t == '¡']
        tot = sum(count)
        return tot

    def interrogaciones(self, tweet):
        tweet = TweetTokenizer().tokenize(tweet)
        tweet = [1 for t in tweet if t == '?' or t == '¿']
        tot = sum(count)
        return tot

    def hashtag(self, tweet):
        tweet = TweetTokenizer().tokenize(tweet)
        tweet = [1 for t in tweet if re.match("^#.", t)]
        tot = sum(count)
        return tot
    
    def elongs():
        tweet = TweetTokenizer().tokenize(tweet)
        tweet = [1 for t in tweet if re.match("^#.", t)]
        tot = sum(count)
        return tot

    def transform(self, X, y=None):
        chars = []
        for tweet in X:
            chars.append(self.mayus(tweet))
            chars.append(self.exclamaciones(tweet))
            chars.append(self.interrogaciones(tweet))
            chars.append(self.hashtag(tweet))
        # return pd.DataFrame(np.array(chars), columns=['tweet'])
        return np.array(chars)

    def fit(self, X, y=None):
        return self    

SyntaxError: invalid syntax (<ipython-input-101-c1918c15d0f9>, line 23)

# Puede haber personas que al aparecer en tweets representen odio, triteza, etc, como trump. Pero eso no significa necesariamente que eso va a ser siempre así

# * Yo creo que es mejor eliminar los usuarios

# Cómo sé a qué intensidad corresponde cada probabilidad??


# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### Definir la representación y el clasificador

Para esto, definiremos Pipelines. Un `Pipeline` es una lista de transformaciones y un estimador(clasificador) ubicado al final el cual define el flujo que seguiran nuestros datos dentro del sistema que creemos. Nos permite ejecutar facilmente el mismo proceso sobre todos los datasets que usemos, simplificando así nuestra programación.

El pipeline más básico que podemos hacer es transformar el dataset a Bag of Words y después usar clasificar el BoW usando NaiveBayes:

```python
    Pipeline([('bow', CountVectorizer()), ('clf', MultinomialNB())])
```


Ahora, si queremos usar nuestra transformación para agregar las features que creamos, usaremos `FeatureUnion`. Esta simplemente concatenará los vectores resultantes de ejecutar BoW y los Transformer en un solo vector.

```python
    Pipeline([('features',FeatureUnion([('bow', CountVectorizer()),
                                        ('chars_count',CharsCountTransformer())])),
              ('clf', MultinomialNB())])

```





Recuerden que cada pipeline representa un sistema de clasificación distinto. Por lo mismo, deben instanciar uno por cada problema que resuelvan. De lo contrario, podrían solapar resultados.  Para esto, les recomendamos crear los pipeline en distintas funciones, como la siguiente:

In [55]:
from sklearn.feature_extraction.text import TfidfTransformer
def get_experiment_0_pipeline():
    return Pipeline([('pre', Preprocessing()),
                     ('features', FeatureUnion([TfidfVectorizer(ngram_range=(1,3), lowercase = True)),
                                                ]),
                     ('clf', RandomForestClassifier())
                     ])

### Ejecutar el pipeline para algún dataset

In [62]:
def run(dataset, dataset_name, pipeline, n_feat):
    """Creamos el pipeline y luego lo ejecutamos el pipeline sobre un dataset. 
    Retorna el modelo ya entrenado mas sus labels asociadas y los scores obtenidos al evaluarlo."""

    # print('run_', 1, dataset_name)
    # Dividimos el dataset en train y test, aún no se transforma de Strings a valores numéricos.
    X_train, X_test, y_train, y_test = train_test_split(
        dataset.tweet,
        dataset.sentiment_intensity,
        shuffle=True,
        test_size=0.22,
        stratify=dataset["class"])
    
    # print('run_', 2, dataset_name)
    print(f'# Datos de entrenamiento en dataset {dataset_name}: {len(X_train)}')
    print(f'# Datos de testing en dataset {dataset_name}: {len(X_test)}')

    # print('run_', 3, dataset_name)
    X_train = pipeline['pre'].transform(X_train)
    # print(X_train)

    pipeline.set_params(bow__max_features=n_feat)
    # print('run_', 4, dataset_name)
    X_train = pipeline['bow'].fit_transform(X_train)
    # print('--------------------------\n',X_train)

    # print('run_', 5, dataset_name)
    # Entrenamos el clasificador (Ejecuta el entrenamiento sobre todo el pipeline). 
    # En este caso el Bag of Words es el encargado de transformar de Strings a vectores numéricos.
    pipeline['clf'].fit(X_train, y_train)

    # print('run_', 6, dataset_name)
    # Predecimos las probabilidades de intensidad de cada elemento del set de prueba.
    X_test = pipeline['pre'].transform(X_test)
    X_test = pipeline['bow'].transform(X_test)
    predicted_probabilities = pipeline['clf'].predict_proba(X_test)

    # print('run_', 7, dataset_name)
    # Obtenemos el orden de las clases aprendidas.
    learned_labels = pipeline.classes_
    
    # print('run_', 8, dataset_name)
    # Evaluamos:
    scores = evaluate(predicted_probabilities, y_test, learned_labels, dataset_name)
    # print('run_', 9, dataset_name)
    return pipeline, learned_labels, scores

### Ejecutar el sistema creado por cada train set

Este código crea y entrena los 4 sistemas de clasificación y luego los evalua. Para los experimentos, pueden copiar este código variando el pipeline cuantas veces estimen conveniente.

In [63]:
classifiers = []
learned_labels_array = []
scores_array = []

# Por cada nombre_dataset, dataset en train ('anger', 'fear', 'joy', 'sadness')
for dataset_name, dataset in train.items():
    
    # creamos el pipeline
    pipeline = get_experiment_0_pipeline()
    
    # ejecutamos el pipeline sobre el dataset
    classifier, learned_labels, scores = run(dataset, dataset_name, pipeline, n_feat=10000)

    # guardamos el clasificador entrenado (en realidad es el pipeline ya entrenado...)
    classifiers.append(classifier)

    # guardamos las labels aprendidas por el clasificador
    learned_labels_array.append(learned_labels)

    # guardamos los scores obtenidos
    scores_array.append(scores)

# print avg scores
print(
    "Average scores:\n\n",
    "Average AUC: {0:.3g}\t Average Kappa: {1:.3g}\t Average Accuracy: {2:.3g}"
    .format(*np.array(scores_array).mean(axis=0)))

# Datos de entrenamiento en dataset anger: 733
# Datos de testing en dataset anger: 208
Confusion Matrix for anger:

[[  9  31   0]
 [  6 128   3]
 [  0  27   4]]

Classification Report:

              precision    recall  f1-score   support

         low       0.60      0.23      0.33        40
      medium       0.69      0.93      0.79       137
        high       0.57      0.13      0.21        31

    accuracy                           0.68       208
   macro avg       0.62      0.43      0.44       208
weighted avg       0.65      0.68      0.62       208

Scores:

AUC:  0.646	Kappa: 0.179	Accuracy: 0.678
------------------------------------------------------

# Datos de entrenamiento en dataset fear: 980
# Datos de testing en dataset fear: 277
Confusion Matrix for fear:

[[ 22  33   0]
 [ 28 120  14]
 [  3  38  19]]

Classification Report:

              precision    recall  f1-score   support

         low       0.42      0.40      0.41        55
      medium       0.63      0.

- Original: Average AUC: 0.643	 Average Kappa: 0.148	 Average Accuracy: 0.582

- Con tf-idf: Average AUC: 0.595	 Average Kappa: 0.0107	 Average Accuracy: 0.564


### Predecir los target set y crear la submission

Aquí predecimos los target set usando los clasificadores creados y creamos los archivos de las submissions.

In [ ]:
def predict_target(dataset, classifier, labels):
    # Predecir las probabilidades de intensidad de cada elemento del target set.
    predicted = pd.DataFrame(classifier.predict_proba(dataset.tweet), columns=labels)
    
    # Agregar ids
    predicted['id'] = dataset.id.values
    # Reordenar las columnas
    predicted = predicted[['id', 'low', 'medium', 'high']]
    return predicted

In [ ]:
predicted_target = {}

# Crear carpeta ./predictions
if (not os.path.exists('./predictions')):
    os.mkdir('./predictions')

else:
    # Eliminar predicciones anteriores:
    shutil.rmtree('./predictions')
    os.mkdir('./predictions')

# por cada target set:
for idx, key in enumerate(target):
    # Predecirlo
    predicted_target[key] = predict_target(target[key], classifiers[idx],
                                           learned_labels_array[idx])
    # Guardar predicciones en archivos separados. 
    predicted_target[key].to_csv('./predictions/{}-pred.txt'.format(key),
                                 sep='\t',
                                 header=False,
                                 index=False)

# Crear archivo zip
a = shutil.make_archive('predictions', 'zip', './predictions')

## **7. Resultados**

    Muestre y analice sus resultados aquí

A continuación una tabla de ejemplo para mostrar los resultados.  En este caso sólo está el experimento del baseline más otro clasificador, pero ustedes debiesen generar una mayor cantidad de experimentos. 

| No. | Approach                       || Dataset   | AUC   | Kappa | Accuracy |
|-----|--------------------------------||-----------|-------|-------|----------|
|     | Features        | Clasifier     |           |       |       |          |
| 0   | bow+chars_count | MultinomialNB | anger     | 0.622 | 0.163 | 0.688    |
|     |                 |               | fear      | 0.597 | 0.091 | 0.559    |
|     |                 |               | joy       | 0.728 | 0.251 | 0.601    |
|     |                 |               | sadness   | 0.645 | 0.166 | 0.581    |
|     |                 |               |**average**| 0.648 | 0.168 | 0.607    |
| 1   | tus features    | tu clasifier  | anger     |       |       |          |
|     |                 |               | fear      |       |       |          |
|     |                 |               | joy       |       |       |          |
|     |                 |               | sadness   |       |       |          |
|     |                 |               |**average**|       |       |          |


## **8. Conclusiones**

    Escriba aquí sus conclusiones

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=582f878d-757e-40fd-9ec6-44a661c7fd78' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>